#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: ImageOverrides
name: redis-image-overrides
overrides:
- image: k8s.gcr.io/redis:e2e
  newImage: redis:6.0.5 #! Use same redis version as one used for redis-slave
---
apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
name: frontend-sources
sources:
- image: gcr.io/google_samples/gb-frontend-arm64:v5
  path: frontend
#! - image: gcr.io/google_samples/gb-redisslave-arm64:v2
#!   path: redis-slave

#@ if/end data.values.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: gcr.io/google_samples/gb-frontend-arm64:v5
  newImage: #@ data.values.push_images_repo + "/kbld-gb-frontend"
- image: gcr.io/google_samples/gb-redisslave-arm64:v2
  newImage: #@ data.values.push_images_repo + "/kbld-gb-redisslave"
