#@ load("@ytt:data", "data")

#@ frontend_port = 80

#@ def labels():
frontend: ""
#@ end

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: #@ frontend_port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  annotations:
    kapp.k14s.io/update-strategy: fallback-on-replace
spec:
  replicas: 1
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: frontend
        image: gcr.io/google_samples/gb-frontend-arm64:v5
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        envFrom:
        - configMapRef:
            name: frontend-config
        ports:
        - containerPort: #@ frontend_port
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  annotations:
    kapp.k14s.io/versioned: ""
data:
  GUESTBOOK_REDIS_PORT: #@ str(data.values.redis_port)
  GUESTBOOK_BG: "#eee"
